#!/bin/bash

if ! snapctl is-connected lomiri-ui-toolkit; then
    echo "The 'lomiri-ui-toolkit' is not connected to this Snap."
    echo "Please run following command:"
    echo ""
    echo "sudo snap install lomiri-ui-toolkit-core24"
    echo "sudo snap connect ${SNAP_INSTANCE_NAME}:lomiri-ui-toolkit lomiri-ui-toolkit-core24"
    exit 1
fi

exec "$SNAP/lomiri-ui-toolkit/bin/lomiri-launch-internal" "$@"
