name: lomiri-ui-toolkit-core24
version: "24.04-2.0"
summary: A convergent UI toolkit for all formfactors
description: |
  Lomiri UI Toolkit

  Lomiri UI Toolkit offers elements for graphical applications to make beautiful interfaces for your app.

  It is built on top of Qt5, Qt6 & QML and offers support for a wide variety of form factors.

  Your app can:

  - Run on smartphones, tablets, laptops & desktops
  - Use hardware acceleration by default
  - Quickly allow for functional apps with less effort

  Want to start magic? Use Lomiri UI Toolkit! 😊

  Lomiri by UBports is the continuation of the Unity8 efforts by Canonical Ltd.
compression: lzo
grade: stable
confinement: strict
base: core24

package-repositories:
  - type: apt
    url: http://repo.ubports.com/
    key-id: B551C909D750AA744948E9ED4BD4B4D6DBB583F1
    components: [ main ]
    suites: [ 24.04-2.x ]

lint:
  ignore:
    - library

platforms:
  amd64:
    build-on: amd64
  arm64:
    build-on: arm64
  armhf:
    build-on: armhf

slots:
  lomiri-ui-toolkit:
    content: lomiri-ui-toolkit
    interface: content
    read:
      - $SNAP

parts:
  lomiri-platform:
    plugin: nil
    stage-packages:
        # Qt5 starting here
        - qmlscene
        - suru-icon-theme
        - hicolor-icon-theme
        - libbluetooth3
        - liblttng-ust1t64
        - libnuma1
        - liburcu8t64
        - libdouble-conversion3
        - libegl1
        - libevdev2
        - libfreetype6
        - libgl1
        - libglvnd0
        - libglx0
        - libgraphite2-3
        - libharfbuzz0b
        - libicu74
        - libpcre2-16-0
        - libpng16-16t64
        - libqt5core5t64
        - libqt5dbus5t64
        - libqt5network5t64
        - libqt5qml5
        - libqt5test5t64
        - libqt5widgets5t64
        - libqt5organizer5a
        - libqt5systeminfo5
        - libx11-6
        - libxau6
        - libxcb1
        - libxdmcp6
        - libxext6
        - libxi6
        - libqt5webengine5
        - libqt5webengine-data
        - libqt5webenginecore5
        - libqt5webenginewidgets5
        - morph-webapp-container-qt6
        - qml-module-morph-web
        - qml-module-qtfeedback
        - qml-module-qtgraphicaleffects
        - qml-module-qtqml-models2
        - qml-module-qtquick-layouts
        - qml-module-qtquick-localstorage
        - qml-module-qtquick-window2
        - qml-module-qtquick2
        - qml-module-qtquick-controls2
        - qml-module-qtquick-templates2
        - qml-module-qtwebengine
        - qml-module-qtwebchannel
        - qml-module-qtwebsockets
        - qml-module-qtwebview
        - qml-module-qt-labs-settings
        - qml-module-qt3d
        - qml-module-qtmultimedia
        - qml-module-qtquick-scene3d
        - qml-module-qtaudioengine
        - qml-module-qtnfc
        - qml-module-qtquick-shapes
        - qml-module-qtbluetooth
        - qml-module-qtorganizer
        - qml-module-qtquick-templates2
        - qml-module-qtcharts
        - qml-module-qtpositioning
        - qml-module-qtcontacts
        - qml-module-qtpublishsubscribe
        - qml-module-qtquick-window2
        - qml-module-qtdatavisualization
        - qml-module-qtqml
        - qml-module-qtquick-xmllistmodel
        - qml-module-qtfeedback
        - qml-module-qtqml-models2
        - qml-module-qtremoteobjects
        - qml-module-qtgamepad
        - qml-module-qtqml-statemachine
        - qml-module-qtscxml
        - qml-module-qtgraphicaleffects
        - qml-module-qtqml-workerscript2
        - qml-module-qtsensors
        - qml-module-qtgstreamer
        - qml-module-qtquick2
        - qml-module-qtserviceframework
        - qml-module-qt-labs-animation
        - qml-module-qtquick-controls
        - qml-module-qtsysteminfo
        - qml-module-qt-labs-calendar
        - qml-module-qttest
        - qml-module-qt-labs-folderlistmodel
        - qml-module-qt-labs-location
        - qml-module-qtquick-dialogs
        - qml-module-qt-labs-platform
        - qml-module-qtquick-extras
        - qml-module-qt-labs-qmlmodels
        - qml-module-qt-labs-settings
        - qml-module-qt-labs-sharedimage
        - qml-module-qtquick-particles2
        - qml-module-qt-labs-wavefrontmesh
        - qml-module-qtquick-pdf
        - qml-module-qtlocation
        - qml-module-qtquick-privatewidgets
        - qml-module-qtquick-scene2d
        - qml-module-lomiri-action
        - qml-module-lomiri-addressbook
        - qml-module-lomiri-components
        - qml-module-lomiri-components-extras
        - qml-module-lomiri-connectivity
        - qml-module-lomiri-contacts
        - qml-module-lomiri-content
        - qml-module-lomiri-downloadmanager
        - qml-module-lomiri-history
        - qml-module-lomiri-history0.1
        - qml-module-lomiri-keyboard
        - qml-module-lomiri-layouts
        - qml-module-lomiri-metrics
        - qml-module-lomiri-notifications
        - qml-module-lomiri-onlineaccounts
        - qml-module-lomiri-onlineaccounts-client
        - qml-module-lomiri-onlineaccounts-plugin
        - qml-module-lomiri-performancemetrics
        - qml-module-lomiri-pushnotifications
        - qml-module-lomiri-settings-components
        - qml-module-lomiri-settings-fingerprint
        - qml-module-lomiri-settings-menus
        - qml-module-lomiri-settings-vpn
        - qml-module-lomiri-syncmonitor
        - qml-module-lomiri-telephony
        - qml-module-lomiri-telephony0.1
        - qml-module-lomiri-telephony-phonenumber
        - qml-module-lomiri-telephony-phonenumber0.1
        - qml-module-lomiri-test
        - qml-module-lomiri-thumbnailer
        - qml-module-mediascanner0.1
        - qml-module-usermetrics
        - qml-module-qzxing
        - libqt5quickcontrols2-5
        - libqt5quicktemplates2-5
        - libqt5multimedia5
        - libqt5multimediaquick5
        - libqt5multimedia5-plugins
        - libqt5multimediawidgets5
        - libqt5multimediagsttools5
        - libqt5svg5
        - libqt5xml5t64
        - libqt5sql5t64
        - libqt5sql5-sqlite
        - libpulse0
        - libpulse-mainloop-glib0
        - fonts-ubuntu
        - fonts-dejavu
        - fonts-emojione
        - fonts-noto-color-emoji
        - xkb-data
        - gstreamer1.0-plugins-good
        - gstreamer1.0-plugins-bad
        - gstreamer1.0-plugins-ugly
        - liblomiri-url-dispatcher0
        - qml-module-qtquick-controls2-suru
        - maliit-inputcontext-qt5
        - jq
        # Provide a full Qt6 solution
        - qml6-module-gsettings
        - qml6-module-lomiri-action
        - qml6-module-lomiri-downloadmanager
        - qml6-module-qt-labs-animation
        - qml6-module-qt-labs-folderlistmodel
        - qml6-module-qt-labs-platform
        - qml6-module-qt-labs-qmlmodels
        - qml6-module-qt-labs-settings
        - qml6-module-qt-labs-sharedimage
        - qml6-module-qt5compat-graphicaleffects
        - qml6-module-qtcore
        - qml6-module-qtmultimedia
        - qml6-module-qtpositioning
        - qml6-module-qtqml
        - qml6-module-qtqml-models
        - qml6-module-qtqml-statemachine
        - qml6-module-qtqml-workerscript
        - qml6-module-qtqml-xmllistmodel
        - qml6-module-qtquick
        - qml6-module-qtquick-controls
        - qml6-module-qtquick-dialogs
        - qml6-module-qtquick-layouts
        - qml6-module-qtquick-localstorage
        - qml6-module-qtquick-particles
        - qml6-module-qtquick-pdf
        - qml6-module-qtquick-shapes
        - qml6-module-qtquick-templates
        - qml6-module-qtquick-timeline
        - qml6-module-qtquick-tooling
        - qml6-module-qtquick-window
        - qml6-module-qtscxml
        - qml6-module-qtsensors
        - qml6-module-qttest
        - qml6-module-qtwebchannel
        - qml6-module-qtwebengine
        - qml6-module-qtwebengine-controlsdelegates
        - qml6-module-qtwebsockets
        - qml6-module-qtqml-workerscript
        - qml6-module-qtqml-models
        - qml6-module-assets-downloader
        - qml6-module-biometryd
        - qml6-module-gsettings
        - qml6-module-ktactilefeedback
        - qml6-module-lomiri-action
        - qml6-module-lomiri-components
        - qml6-module-lomiri-components-extras
        - qml6-module-lomiri-components-labs
        - qml6-module-lomiri-connectivity
        - qml6-module-lomiri-content
        - qml6-module-lomiri-downloadmanager
        - qml6-module-lomiri-keyboard
        - qml6-module-lomiri-layouts
        - qml6-module-lomiri-metrics
        - qml6-module-lomiri-notifications
        - qml6-module-lomiri-onlineaccounts
        - qml6-module-lomiri-onlineaccounts-client
        - qml6-module-lomiri-onlineaccounts-plugin
        - qml6-module-lomiri-performancemetrics
        - qml6-module-lomiri-pushnotifications
        - qml6-module-lomiri-systeminfo
        - qml6-module-lomiri-thumbnailer
        - qml6-module-mediascanner
        - qml6-module-morph-web
        - qml6-module-ofono
        - qml6-module-qml
        - qml6-module-qmltime
        - qml6-module-qt5compat-graphicaleffects
        - qml6-module-qtcore
        - qml6-module-qt-labs-animation
        - qml6-module-qt-labs-folderlistmodel
        - qml6-module-qt-labs-platform
        - qml6-module-qt-labs-qmlmodels
        - qml6-module-qt-labs-settings
        - qml6-module-qt-labs-sharedimage
        - qml6-module-qt-labs-wavefrontmesh
        - qml6-module-qtlocation
        - qml6-module-qtmultimedia
        - qml6-module-qtnetwork
        - qml6-module-qtpositioning
        - qml6-module-qtqml
        - qml6-module-qtqml-models
        - qml6-module-qtqml-statemachine
        - qml6-module-qtqml-workerscript
        - qml6-module-qtqml-xmllistmodel
        - qml6-module-qtquick
        - qml6-module-qtquick-controls
        - qml6-module-qtquick-controls2-suru
        - qml6-module-qtquick-dialogs
        - qml6-module-qtquick-effects
        - qml6-module-qtquick-layouts
        - qml6-module-qtquick-localstorage
        - qml6-module-qtquick-particles
        - qml6-module-qtquick-pdf
        - qml6-module-qtquick-shapes
        - qml6-module-qtquick-templates
        - qml6-module-qtquick-timeline
        - qml6-module-qtquick-timeline-blendtrees
        - qml6-module-qtquick-tooling
        - qml6-module-qtquick-vectorimage
        - qml6-module-qtquick-window
        - qml6-module-qtscxml
        - qml6-module-qtsensors
        - qml6-module-qttest
        - qml6-module-qtwayland-client-texturesharing
        - qml6-module-qtwayland-compositor
        - qml6-module-qtwebchannel
        - qml6-module-qtwebengine
        - qml6-module-qtwebengine-controlsdelegates
        - qml6-module-qtwebsockets
        - qml6-module-snapd2
        - qml6-module-sso-onlineaccounts
        - maliit-inputcontext-qt6
        - qtwayland5
        - qt6-wayland
    stage:
        - usr/
        - -usr/bin/
        - usr/bin/paplay
        - usr/bin/parec
        - usr/bin/fc-*
        - usr/bin/webapp-container
        - usr/bin/xdg-*
        - -usr/lib/evolution-data-server
        - -usr/lib/emacsen-common
        - -usr/lib/systemd
        - -usr/libexec/evolution-data-server/
        - -usr/libexec/libusermetrics/
        - -usr/libexec/lomiri-history-daemon
        - -usr/libexec/lomiri-thumbnailer/
        - -usr/libexec/mediascanner-2.0/
        - -usr/share/aclocal/
        - -usr/share/applications/
        - -usr/share/apport/
        - -usr/share/bash-completion/
        - -usr/share/click/
        - -usr/share/dbus-1/
        - -usr/share/debconf/
        - -usr/share/directfb-*/
        - -usr/share/doc/
        - -usr/share/evolution-data-server/
        - -usr/share/info/
        - -usr/share/language-tools/
        - -usr/share/polkit-1/
        - -usr/share/perl5/
        - -usr/share/session-migration/
        - -usr/share/telepathy/
        - -usr/share/upstart/
        - -usr/share/zsh/
        - -var/
        - etc/
        - -etc/vulkan/
        - -etc/apparmor/
        - -etc/dbus-1/
        - -etc/deviceinfo/
        - -etc/X11/
        - -lib/click-apparmor/
        - -lib/systemd/
        - -lib/udev/
        # Avoid conflicts with the 'specifics' part
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt5Gui.so.5.*.*
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt5Quick.so.5.*.*
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt5XcbQpa.so.5.*.*
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt5EglFSDeviceIntegration.so.5.*.*
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt5EglFsKmsSupport.so.5.*.*
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/egldeviceintegrations/libqeglfs-emu-integration.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/egldeviceintegrations/libqeglfs-kms-integration.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/egldeviceintegrations/libqeglfs-x11-integration.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/generic/libqevdevkeyboardplugin.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/generic/libqevdevmouseplugin.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/generic/libqevdevtabletplugin.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/generic/libqevdevtouchplugin.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/generic/libqlibinputplugin.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/generic/libqtuiotouchplugin.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/imageformats/libqgif.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/imageformats/libqico.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/imageformats/libqjpeg.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/platforms/libqeglfs.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/platforms/libqlinuxfb.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/platforms/libqminimal.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/platforms/libqminimalegl.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/platforms/libqoffscreen.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/platforms/libqvnc.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/platforms/libqxcb.so
        - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/xcbglintegrations/libqxcb-egl-integration.so

  specifics:
    after:
      - lomiri-platform
    plugin: nil
    stage-packages:
        - on armhf:
            - to armhf:
                - libqt5gui5-gles
                - libqt5quick5-gles
                - cameraplugin-aal
                - qtubuntu-media
                - gst-hybris
                - libqt5sensors5-sensorfw
                - lomiri-location-service-qt5-plugin
                - qtubuntu-android
                - mir1-client-platform-android5
                - mir1-client-platform-android-caf5
                - mir1-client-platform-android2-5
        - on arm64:
            - to arm64:
                - libqt5gui5-gles
                - libqt5quick5-gles
                - cameraplugin-aal
                - qtubuntu-media
                - gst-hybris
                - libqt5sensors5-sensorfw
                - lomiri-location-service-qt5-plugin
                - qtubuntu-android
                - mir1-client-platform-android5
                - mir1-client-platform-android-caf5
                - mir1-client-platform-android2-5
        - on amd64:
            - to amd64:
                - libqt5gui5
                - libqt5quick5

  misc:
    after: [ lomiri-platform, specifics ]
    source: misc
    plugin: dump

  cleanup:
    after:
      - lomiri-platform
      - specifics
      - misc
    plugin: nil
    build-packages: [ execstack ]
    build-snaps: [ mesa-2404 ]
    override-prime: |
      set -eux

      # mesa-2404 provided libraries
      cd /snap/mesa-2404/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      find . -type f,l -exec rm -rf $CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/{} \;
      rm -fr "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
      for CRUFT in bug drirc.d glvnd libdrm lintian man; do
        rm -rf "$CRAFT_PRIME/usr/share/$CRUFT"
      done
      rm -rf $CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liburcu*

      # hybris-2404 provided libraries
      # We can't clean up against hybris-2404 as mainline also links against libhybris
      # right now. We can unify this once QtWebEngine runtime-loads libhybris instead.
      rm -f $CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lib{EGL,GLESv1_CM,GLESv2}_libhybris.so*
      rm -f $CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libhybris/*.so

      # Probably a relict from our custom Mesa build
      rm -rf $CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdrm_*.so*

      # Clear execstack to silence store complaints
      cd $CRAFT_PRIME/usr/lib
      find . -type f -name "*.so*" -exec execstack --clear-execstack {} \;

      # We want emojis & other bitmaps
      if [ -f "$CRAFT_PRIME/etc/fonts/conf.d/70-no-bitmaps-except-emoji.conf" ]; then
        rm -f "$CRAFT_PRIME/etc/fonts/conf.d/70-no-bitmaps-except-emoji.conf"
      fi

      # These have no effect in a Snap
      rm -f $CRAFT_PRIME/usr/bin/aa-*
      for CRUFT in X11 apparmor deviceinfo dbus-1 vulkan glvnd init.d sensorfw; do
        rm -rf "$CRAFT_PRIME/etc/${CRUFT}"
      done
      rm -rf "$CRAFT_PRIME/lib"

      # Usually found on an Ubuntu Touch host
      rm -rf "$CRAFT_PRIME/usr/share/{apparmor,click,dbus-1,doc}"
      rm -rf "$CRAFT_PRIME/usr/sbin"
      rm -rf "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/perl{5,-base}"
      rm -rf "$CRAFT_PRIME/usr/lib/{udev,systemd}"

      # Points to /run
      rm -f $CRAFT_PRIME/etc/pulse/client.conf.d/*-enable-autospawn.conf
