name: lomiri-ui-toolkit-core24
version: "latest"
summary: A convergent UI toolkit for all formfactors
description: |
  Lomiri UI Toolkit

  Lomiri UI Toolkit offers elements for graphical applications to make beautiful interfaces for your app. It is built on top of Qt5 & QML and offers support for a wide variety of form factors.

  Your app can:

  - Run on smartphones, tablets, laptops & desktops
  - Use hardware acceleration by default
  - Quickly allow for functional apps with less effort

  Want to start magic? Use Lomiri UI Toolkit! 😊

  Lomiri by UBports is the continuation of the Unity8 effors by Canonical Ltd.
compression: lzo
grade: stable
confinement: strict
base: core24

platforms:
  amd64:
    build-on: amd64
  arm64:
    build-on: arm64
  armhf:
    build-on: armhf

slots:
  lomiri-ui-toolkit:
    content: lomiri-ui-toolkit
    interface: content
    read:
      - $SNAP

plugs:
  graphics-core24:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-2404

parts:
  suru-icons:
    plugin: nil
    source: https://gitlab.com/ubports/core/suru-icon-theme.git
    source-branch: main
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons
      cp -a $SNAPCRAFT_PART_SRC/suru $SNAPCRAFT_PART_INSTALL/usr/share/icons/
  lomiri-ui-toolkit:
    plugin: qmake
    after: [ suru-icons ]
    qmake-project-file: lomiri-sdk.pro
    qmake-parameters:
        - CONFIG+=ubuntu-uitk-compat
        - CONFIG+=no_docs
        - CONFIG+=debian_build
    source: https://gitlab.com/ubports/core/lomiri-ui-toolkit.git
    source-branch: main
    override-build: |
      rm -rf $SNAPCRAFT_PART_SRC/examples || true
      sed -i "s/ po app-launch-profiler / /g" $SNAPCRAFT_PART_SRC/lomiri-sdk.pro
      sed -i "s/^src_uitk_launcher\./#src_uitk_launcher\./g" $SNAPCRAFT_PART_SRC/lomiri-sdk.pro
      sed -i "s/ src_uitk_launcher apicheck/ /g" $SNAPCRAFT_PART_SRC/lomiri-sdk.pro
      craftctl default
    build-packages:
        - dbus
        - dbus-test-runner
        - devscripts
        - gdb
        - libdbus-1-dev
        - liblttng-ust-dev
        - libqt5svg5-dev
        - libxi-dev
        - qtbase5-private-dev
        - qtdeclarative5-private-dev
        - qml-module-qtfeedback
        - qml-module-qtquick2
        - qml-module-qtquick-window2
        - qml-module-qtquick-layouts
        - qml-module-qtgraphicaleffects
        - qml-module-qttest
        - qml-module-qtfeedback
        - qtsystems5-dev
        - qtsystems5-private-dev
        - qtpim5-dev
    stage-packages:
        - on armhf:
            - to armhf:
                - libqt5gui5-gles
                - libqt5quick5-gles
        - on arm64:
            - to arm64:
                - libqt5gui5-gles
                - libqt5quick5-gles
        - on amd64:
            - to amd64:
                - libqt5gui5
                - libqt5quick5
        - fonts-ubuntu
        - yaru-theme-icon
        - libbluetooth3
        - liblttng-ust1t64
        - libnuma1
        - liburcu8t64
        - libdouble-conversion3
        - libegl1
        - libevdev2
        - libfreetype6
        - libgl1
        - libglvnd0
        - libglx0
        - libgraphite2-3
        - libharfbuzz0b
        - libicu74
        - libpcre2-16-0
        - libpng16-16t64
        - libqt5core5t64
        - libqt5dbus5t64
        - libqt5network5t64
        - libqt5qml5
        - libqt5test5t64
        - libqt5widgets5t64
        - libqt5organizer5a
        - libqt5systeminfo5
        - libx11-6
        - libxau6
        - libxcb1
        - libxdmcp6
        - libxext6
        - libxi6
        - qml-module-qtfeedback
        - qml-module-qtgraphicaleffects
        - qml-module-qtqml-models2
        - qml-module-qtquick-layouts
        - qml-module-qtquick-localstorage
        - qml-module-qtquick-window2
        - qml-module-qtquick2
        - qml-module-qtquick-controls2
        - qml-module-qtquick-templates2
        - libqt5quickcontrols2-5
        - libqt5quicktemplates2-5
        - qtwayland5

  content-hub:
    plugin: cmake
    source: https://gitlab.com/ubports/development/core/lomiri-content-hub.git
    source-branch: main
    cmake-parameters:
        - -DCMAKE_INSTALL_PREFIX=/usr
        - -DENABLE_TESTS=OFF
        - -DENABLE_DOC=OFF
        - -DENABLE_UBUNTU_COMPAT=ON
    build-packages:
        - cmake-extras
        - doxygen
        - graphviz
        - gettext
        - libgtest-dev
        - libapparmor-dev
        - libdbus-1-dev
        - libglib2.0-dev
        - libgsettings-qt-dev
        - liblomiri-api-dev
        - libnotify-dev
        - liblomiri-download-manager-client-dev
        - liblomiri-app-launch-dev
        - qml-module-lomiri-components
        - qml-module-qtquick2
        - qml-module-qttest
        - qtbase5-dev
        - qtdeclarative5-dev
        - qtdeclarative5-dev-tools
        - qttools5-dev-tools
    stage-packages:
        - liblomiri-app-launch0
        - liblomiri-download-manager-client0t64
        - liblomiri-download-manager-common0t64
        - libgdk-pixbuf-2.0-0
        - liblomiri-api0
        - libnotify4
    after: [ lomiri-ui-toolkit ]

  quickcontrolssuru:
    plugin: qmake
    source: https://gitlab.com/ubports/development/core/qqc2-suru-style.git
    source-branch: main
    qmake-project-file: suru.pro
    build-packages:
        - qtquickcontrols2-5-dev
        - qtquickcontrols2-5-private-dev
        - qtdeclarative5-dev
        - qtdeclarative5-private-dev
        - qtdeclarative5-dev-tools
        - qtbase5-dev
        - qtbase5-private-dev
        - qt5-qmake
        - pkg-kde-tools
    after: [ content-hub ]

  qt-setup:
    after: [ quickcontrolssuru ]
    source: https://github.com/snapcore/snapcraft-desktop-integration.git
    plugin: nil
    override-build: |
      cd qt-framework
      make PLATFORM_PLUG=desktop DESTDIR=$SNAPCRAFT_PART_INSTALL install
    stage:
      - command-chain
  wrappers:
    after: [ qt-setup ]
    source: snap/local
    plugin: dump

  cleanup:
    after: [ wrappers ]
    plugin: nil
    build-snaps: [ mesa-2404 ]
    override-prime: |
      set -eux
      cd /snap/mesa-2404/current/usr/lib/${CRAFT_ARCH_TRIPLET}
      find . -type f,l -exec rm -f $CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/{} \;
      rm -fr "$CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/dri"
      for CRUFT in bug drirc.d glvnd libdrm lintian man; do
        rm -rf "$CRAFT_PRIME/usr/share/$CRUFT"
      done
      for CRUFT in libpulse-simple liburcu; do
        rm -rf "$CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/${CRUFT}*"
      done

